// data/Artworks.js

export const artworks = [
  {
    id: "sofonisba-anguissola-portrait",
    title: "Portrait of a Young Woman",
    artist: {
      id: "sofonisba-anguissola",
      name: "Sofonisba Anguissola",
      nationality: "Italian",
      birthYear: 1532,
      deathYear: 1625,
      period: "Renaissance",
    },
    medium: "Oil on canvas",
    dimensions: "50 cm × 40 cm",
    location: "Private collection",
    objectDate: "c. 1560",
    image: "https://upload.wikimedia.org/wikipedia/commons/6/6b/Sofonisba_Anguissola_-_Portrait_of_a_Young_Woman.jpg",
    description: "A delicate Renaissance portrait showcasing Anguissola's mastery of subtle expression and refined detail.",
    period: "Renaissance",
    repository: "Private collection",
  },
  {
    id: "fayum-mummy-portrait",
    title: "Fayum Mummy Portrait",
    artist: {
      id: "unknown-fayum",
      name: "Unknown Egyptian Artist",
      nationality: "Egyptian",
      birthYear: null,
      deathYear: null,
      period: "Roman Egypt",
    },
    medium: "Encaustic on wood",
    dimensions: "35 cm × 25 cm",
    location: "Metropolitan Museum of Art, New York",
    objectDate: "c. 100-150 CE",
    image: "https://upload.wikimedia.org/wikipedia/commons/f/f6/Fayum-mummy-portrait-Met.jpg",
    description: "A lifelike portrait of a woman from Roman Egypt, reflecting the fusion of Egyptian and Greco-Roman artistic traditions.",
    period: "Roman Egypt",
    repository: "Metropolitan Museum of Art",
  },
  {
    id: "camille-claudel-the-waltz",
    title: "The Waltz",
    artist: {
      id: "camille-claudel",
      name: "Camille Claudel",
      nationality: "French",
      birthYear: 1864,
      deathYear: 1943,
      period: "Modern",
    },
    medium: "Bronze sculpture",
    dimensions: "35 cm × 25 cm × 20 cm",
    location: "Musée Rodin, Paris",
    objectDate: "c. 1889-1905",
    image: "https://upload.wikimedia.org/wikipedia/commons/7/79/Camille_Claudel_-_La_valse_-_Musee_Rodin.jpg",
    description: "A dynamic sculpture capturing the grace and fluidity of dancers, showcasing Claudel's emotional intensity and technical skill.",
    period: "Modern",
    repository: "Musée Rodin",
  },
  {
    id: "hilma-af-klint",
    title: "Primordial Chaos",
    artist: {
      id: "hilma-af-klint",
      name: "Hilma af Klint",
      nationality: "Swedish",
      birthYear: 1862,
      deathYear: 1944,
      period: "Abstract/Modern",
    },
    medium: "Oil on canvas",
    dimensions: "180 cm × 180 cm",
    location: "Private collection",
    objectDate: "1906",
    image: "https://upload.wikimedia.org/wikipedia/commons/1/1b/Hilma_af_Klint_-_Primordial_Chaos.jpg",
    description: "An early abstract painting exploring spiritual themes through color and geometry, predating much of the abstract movement.",
    period: "Abstract/Modern",
    repository: "Private collection",
  },
  {
    id: "eileen-agar-moonlight",
    title: "Moonlight",
    artist: {
      id: "eileen-agar",
      name: "Eileen Agar",
      nationality: "British",
      birthYear: 1899,
      deathYear: 1991,
      period: "Surrealism",
    },
    medium: "Oil on canvas",
    dimensions: "60 cm × 50 cm",
    location: "Tate Britain, London",
    objectDate: "c. 1930",
    image: "https://upload.wikimedia.org/wikipedia/commons/5/55/Eileen_Agar_-_Moonlight.jpg",
    description: "A surrealist painting blending dreamlike imagery and abstraction, highlighting Agar's innovative use of light and color.",
    period: "Surrealism",
    repository: "Tate Britain",
  },
  {
    id: "lee-krasner-composition",
    title: "Composition",
    artist: {
      id: "lee-krasner",
      name: "Lee Krasner",
      nationality: "American",
      birthYear: 1908,
      deathYear: 1984,
      period: "Abstract Expressionism",
    },
    medium: "Oil on canvas",
    dimensions: "152 cm × 203 cm",
    location: "Private collection",
    objectDate: "c. 1949",
    image: "https://upload.wikimedia.org/wikipedia/commons/3/37/Lee_Krasner_-_Composition.jpg",
    description: "A bold abstract expressionist work, showcasing Krasner's dynamic brushwork and pioneering contributions to post-war American art.",
    period: "Abstract Expressionism",
    repository: "Private collection",
  }
];
